name: ecommerce_delivery_app_php
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^10.0.0
  get: ^4.6.1
  # DateTime
  jiffy: ^6.3.2
  intl: ^0.19.0
  http: ^1.3.0
  # Images
  cached_network_image: ^3.2.0
  image_picker: ^1.1.2
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  # Firebase And Notification
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.1.0
  cloud_firestore: ^5.6.6
  googleapis_auth: ^2.0.0
  firebase_cloud_firestore: ^5.4.4
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  grouped_list: ^6.0.0
  url_launcher: ^6.1.2
  dropdown_search: ^6.0.2
  badges: ^3.1.2
  # scan: ^1.6.0
  # Icon
  # flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.3.0
  device_preview: ^1.2.0
  responsive_builder: ^0.7.1
  image_pickers: ^2.0.0+2
  flutter_svg: ^2.0.17
  flutter_otp_text_field: ^1.5.1+1
  timelines:
  lottie: ^3.3.1
  rating_dialog: ^2.0.4
  flutter_ringtone_player:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - HTTP_V1/ecommerceapp-7851c-firebase-adminsdk-fbsvc-9095f91b1f.json
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
